server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        register-enabled: true
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: stock-route
          uri: lb://product-stock-service
          predicates:
            - Path=/api/stock/**

        - id: seckill-route
          uri: lb://seckill-service
          predicates:
            - Path=/api/seckill/**

        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
